// <auto-generated />
using System;
using MailRuEncryptedCloud.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MailRuEncryptedCloud.Migrations
{
    [DbContext(typeof(DirDbContext))]
    partial class DirDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MailRuEncryptedCloud.DB.Models.EncryptedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("EncryptedName")
                        .HasMaxLength(50);

                    b.Property<byte[]>("EnryptedHash")
                        .HasMaxLength(256);

                    b.Property<int>("FolderId");

                    b.Property<byte[]>("Hash")
                        .HasMaxLength(256);

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .HasMaxLength(260);

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("MailRuEncryptedCloud.DB.Models.EncryptedFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("EncryptedName")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(260);

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("MailRuEncryptedCloud.DB.Models.EncryptedFile", b =>
                {
                    b.HasOne("MailRuEncryptedCloud.DB.Models.EncryptedFolder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MailRuEncryptedCloud.DB.Models.EncryptedFolder", b =>
                {
                    b.HasOne("MailRuEncryptedCloud.DB.Models.EncryptedFolder", "Parent")
                        .WithMany("Folders")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
